# Generated by Django 5.2.10 on 2026-02-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foto', '0002_alter_fotobooking_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotobooking',
            options={'ordering': ['-start_date', '-start_time'], 'verbose_name': 'Foto Booking', 'verbose_name_plural': 'Foto Bookinger'},
        ),
    ]
