# Generated by Django 5.1.6 on 2025-09-22 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_event_eventmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(db_index=True, default='test', max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TeamEventMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='events',
            field=models.ManyToManyField(db_index=True, through='organization.TeamEventMembership', to='organization.event'),
        ),
    ]
