# Generated by Django 5.2.10 on 2026-04-13 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0017_remove_historicalteam_discord_webhook_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='DepotItem/')),
                ('total_quantity', models.IntegerField(default=1, help_text='Total quantity available in inventory')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Depot Item',
                'verbose_name_plural': 'Depot Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Quantity requested')),
                ('start', models.DateTimeField(verbose_name='Start datetime')),
                ('end', models.DateTimeField(verbose_name='End datetime')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Udleveret', 'Udleveret')], db_index=True, default='Pending', max_length=10)),
                ('remarks', models.TextField(blank=True, help_text='Booking remarks')),
                ('admin_comment', models.TextField(blank=True, help_text='Admin comment on booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.team')),
                ('team_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Depot.depotitem')),
            ],
            options={
                'verbose_name': 'Depot Booking',
                'verbose_name_plural': 'Depot Bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item', 'status'], name='Depot_depot_item_id_0c7352_idx'), models.Index(fields=['team', 'status'], name='Depot_depot_team_id_7dc187_idx'), models.Index(fields=['start', 'end'], name='Depot_depot_start_286637_idx')],
            },
        ),
    ]


