# Generated by Django 5.2.10 on 2026-04-13 19:08

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depot', '0001_initial'),
        ('organization', '0017_remove_historicalteam_discord_webhook_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depotbooking',
            options={'ordering': ['-start_date', '-start_time'], 'verbose_name': 'Depot Booking', 'verbose_name_plural': 'Depot Bookings'},
        ),
        migrations.RemoveIndex(
            model_name='depotbooking',
            name='Depot_depot_start_286637_idx',
        ),
        migrations.RemoveField(
            model_name='depotbooking',
            name='end',
        ),
        migrations.RemoveField(
            model_name='depotbooking',
            name='start',
        ),
        migrations.AddField(
            model_name='depotbooking',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depotbooking',
            name='end_time',
            field=models.TimeField(default='17:00', verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='depotbooking',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depotbooking',
            name='start_time',
            field=models.TimeField(default='08:00', verbose_name='Start time'),
        ),
        migrations.AddIndex(
            model_name='depotbooking',
            index=models.Index(fields=['start_date', 'end_date'], name='Depot_depot_start_d_8fa6b2_idx'),
        ),
    ]

