# Generated by Django 5.2.10 on 2026-04-13 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depot', '0002_alter_depotbooking_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepotLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Depot Location',
                'verbose_name_plural': 'Depot Locations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='depotitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Depot.depotlocation'),
        ),
    ]

