# Generated by Django 5.2.10 on 2026-04-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depot', '0003_depotlocation_depotitem_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depotitem',
            old_name='total_quantity',
            new_name='quantity',
        ),
    ]

