# Generated by Django 5.2.10 on 2026-04-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depot', '0004_rename_total_quantity_depotitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='depotitem',
            name='unit',
            field=models.CharField(default='stk', help_text='Unit of measurement (e.g., stk, liter, kg, m, etc.)', max_length=50),
        ),
    ]
