# Generated by Django 5.2.10 on 2026-01-20 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sjak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sjakitem',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sjak.sjakitemtype'),
        ),
    ]
