# Generated by Django 5.2.10 on 2026-02-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sjak', '0002_alter_sjakitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sjakbooking',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sjak_bookings/', verbose_name='Billede'),
        ),
    ]
