# Generated by Django 5.2.10 on 2026-03-12 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sjak', '0003_sjakbooking_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sjakbooking',
            name='assigned_sjak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sjak_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Staff'),
        ),
        migrations.AddField(
            model_name='sjakbooking',
            name='tag',
            field=models.CharField(blank=True, choices=[('Urgent', 'Urgent'), ('Low Priority', 'Low Priority'), ('In Review', 'In Review'), ('Blocked', 'Blocked')], default=None, max_length=20, null=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='sjakbooking',
            name='status_internal',
            field=models.CharField(choices=[('Afventer', 'Afventer'), ('Igang', 'Igang'), ('Klar', 'Klar'), ('Afsluttet', 'Afsluttet')], default='Afventer', max_length=20),
        ),
    ]


