# Generated by Django 5.2.10 on 2026-03-12 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sjak', '0004_sjakbooking_assigned_sjak_sjakbooking_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SjakTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('color', models.CharField(default='#0d6efd', help_text='Hex color code (e.g., #dc3545)', max_length=7)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sjak Tag',
                'verbose_name_plural': 'Sjak Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='sjakbooking',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='Sjak.sjaktag', verbose_name='Tag'),
        ),
    ]

