# Generated by Django 5.2.10 on 2026-04-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sjak', '0005_sjaktag_alter_sjakbooking_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sjakbooking',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='sjakbooking',
            old_name='start',
            new_name='start_date',
        ),
    ]
