# Generated by Django 5.2.10 on 2026-02-04 15:58

import map_location.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teknik', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teknikbooking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='teknikbooking',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='teknikbooking',
            name='longitude',
        ),
        migrations.AddField(
            model_name='teknikbooking',
            name='location',
            field=map_location.fields.LocationField(blank=True, default='56.114951,9.655592', null=True, verbose_name='Lokation'),
        ),
    ]
