# Generated by Django 5.1.6 on 2025-09-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_team_short_name_teameventmembership_team_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='events',
            field=models.ManyToManyField(blank=True, db_index=True, through='organization.EventMembership', to='organization.event'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='teams',
            field=models.ManyToManyField(blank=True, db_index=True, through='organization.TeamMembership', to='organization.team'),
        ),
    ]
