# Generated by Django 5.1.6 on 2025-09-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_volunteer_events_volunteer_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
