# Generated by Django 5.2.10 on 2026-02-02 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_historicalteam_historicalkey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Afventer (Pending)'), ('accepted', 'Accepteret'), ('rejected', 'Afvist'), ('cancelled', 'Annulleret')], default='pending', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_appointments', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aftale',
            },
        ),
    ]
