# Generated by Django 5.2.10 on 2026-02-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_volunteerappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerappointment',
            name='end_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerappointment',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerappointment',
            name='end_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerappointment',
            name='start_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
