# Generated by Django 5.2.10 on 2026-02-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_volunteerappointment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerappointment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerappointment',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerappointment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerappointment',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
