# Generated by Django 5.2.10 on 2026-03-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_alter_volunteerappointment_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvolunteer',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='volunteer_profiles/'),
        ),
    ]


