# Generated by Django 5.2.10 on 2026-03-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_historicalvolunteer_image_volunteer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvolunteer',
            name='image_thumbnail',
            field=models.TextField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='image_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='volunteer_profiles/thumbnails/'),
        ),
    ]
