# Generated by Django 5.2.10 on 2026-03-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_historicalvolunteer_image_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalteam',
            name='discord_webhook_key',
            field=models.CharField(blank=True, help_text="Discord webhook key for daily summaries (e.g., 'channel-name' for mailrise@channel-name)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalvolunteer',
            name='discord_id',
            field=models.CharField(blank=True, help_text="Discord user ID for @mention functionality (e.g., '123456789')", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='discord_webhook_key',
            field=models.CharField(blank=True, help_text="Discord webhook key for daily summaries (e.g., 'channel-name' for mailrise@channel-name)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='discord_id',
            field=models.CharField(blank=True, help_text="Discord user ID for @mention functionality (e.g., '123456789')", max_length=30, null=True),
        ),
    ]


