# Generated by Django 5.2.10 on 2026-03-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_historicalteam_discord_webhook_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalteam',
            name='discord_webhook_url',
            field=models.URLField(blank=True, help_text='Discord webhook URL for real-time notifications. Get this from Server Settings > Integrations > Webhooks > Copy Webhook URL', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='discord_webhook_url',
            field=models.URLField(blank=True, help_text='Discord webhook URL for real-time notifications. Get this from Server Settings > Integrations > Webhooks > Copy Webhook URL', null=True),
        ),
    ]
