# Generated by Django 5.2.10 on 2026-03-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_historicalteam_discord_webhook_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalteam',
            name='discord_webhook_key',
        ),
        migrations.RemoveField(
            model_name='team',
            name='discord_webhook_key',
        ),
    ]

