"""
Django settings for bookingsystem project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy
from pathlib import Path
from dotenv import load_dotenv
import os

import os
from pathlib import Path

# Load .env files locally (optional)

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'slettenbooking@gmail.com')

# Debug setting
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Secret key
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'dev-secret-key-change-in-production')

# Allowed hosts
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Environment detection
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'dev')

# Database configuration
if ENVIRONMENT in ['staging', 'production']:
    # Use PostgreSQL for staging/production
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DATABASE_NAME'),
            'USER': os.environ.get('DATABASE_USERNAME'),
            'PASSWORD': os.environ.get('DATABASE_PASSWORD'),
            'HOST': os.environ.get('DATABASE_HOST', 'db'),
            'PORT': os.environ.get('DATABASE_PORT', '5432'),
        }
    }
else:
    # Use SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# -----------------------------
# Static files
# -----------------------------
STATIC_URL = 'static/'

STATIC_ROOT = '/vol/web/static/' 


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    "unfold.contrib.constance",  # optional, if django-constance package is used
    "django.contrib.admin",  # required
    'django_comments_xtd',
    'django_comments',
    'django.contrib.sites',  # Required by django-comments
    'organization',
    'django.contrib.staticfiles',
    'import_export',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django_webpack_dev_server',
    'frontend',
    'core',
    'django_bootstrap5',
    'template_partials',
    'django_bootstrap_icons',
    'django_admin_listfilter_dropdown',
    'AktivitetsTeam',
    'Butikken',
    'Sjak',
    'Teknik'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'core.wsgi.application'



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'da-dk'
LANGUAGES = (
    ('da', 'Danish'),
    ('no', 'Norwegian'),
    ('en', 'English'),
)

TIME_ZONE = 'Europe/Copenhagen'
USE_L10N = True
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


SITE_ID = 1  # Required for django.contrib.sites

# Basic XTD Settings
COMMENTS_APP = 'django_comments_xtd'
COMMENTS_XTD_MAX_THREAD_LEVEL = 2  # How deep the replies go
COMMENTS_XTD_CONFIRM_EMAIL = False # Set to True if you want email verification


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'organization.Volunteer'

UNFOLD = {
    "SITE_TITLE": "Admin",
    "SITE_HEADER": "SKS Admin",
    "SITE_SUBHEADER": "- Med lort på styret",
    "SITE_SYMBOL": "mode_heat",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": True,
    "BORDER_RADIUS": "6px",
    "COLORS": {
        "primary": {
            50: "#FFF0EB",
            100: "#FFE2D6",
            200: "#FFC8B3",
            300: "#FFAB8A",
            400: "#FF8E61",
            500: "#FF733C",
            600: "#FF733C",
            700: "#FF733C",
            800: "#FA4700",
            900: "#BD3500",
            950: "#802400",
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "dn": "🇩🇰",
                "en": "🇬🇧",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Organization"),
                "separator": True,
                "collapsible": True,
                "default_open": True,
                "items": [
                    {
                        "title": _("Brugere"),
                        "icon": "person",
                        "link": reverse_lazy("admin:organization_volunteer_changelist"),
                    },
                    {
                        "title": _("Teams"),
                        "icon": "people",
                        "link": reverse_lazy("admin:organization_team_changelist"),
                    },
                    {
                        "title": _("Events"),
                        "icon": "event",
                        "link": reverse_lazy("admin:organization_event_changelist"),
                    },
                ],
            },
            {
                "title": _("Butikken & Forplejning"),  # Added Butikken Section
                "separator": True,
                "collapsible": True,
                "default_open": True,
                "items": [
                    {
                        "title": _("Vareoversigt"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:Butikken_butikkenitem_changelist"),
                    },
                    {
                        "title": _("Vare Bookinger"),
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:Butikken_butikkenbooking_changelist"),
                    },
                    {
                        "title": _("Måltider"),
                        "icon": "restaurant_menu",
                        "link": reverse_lazy("admin:Butikken_mealplan_changelist"),
                    },
                    {
                        "title": _("Team Måltidsvalg"),
                        "icon": "assignment",
                        "link": reverse_lazy("admin:Butikken_teammealplan_changelist"),
                    },
                    {
                        "title": _("Opskrifter"),
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:Butikken_recipe_changelist"),
                    },
                ],
            },
            {
                "title": _("Aktivitetsteam"),
                "separator": True,
                "collapsible": True,
                "default_open": True,
                "items": [
                    {
                        "title": _("Bookinger"),
                        "icon": "calendar_add_on",
                        "link": reverse_lazy("admin:AktivitetsTeam_aktivitetsteambooking_changelist"),
                    },
                    {
                        "title": _("Aktiviteter"),
                        "icon": "hiking",
                        "link": reverse_lazy("admin:AktivitetsTeam_aktivitetsteamitem_changelist"),
                    },
                ],
            },
            {
                "title": _("Sjak"),
                "separator": True,
                "collapsible": True,
                "default_open": True,
                "items": [
                    {
                        "title": _("Sjak Bookinger"),
                        "icon": "calendar_add_on",
                        "link": reverse_lazy("admin:Sjak_sjakbooking_changelist"),
                    },
                    {
                        "title": _("Sjak sager"),
                        "icon": "home_repair_service",
                        "link": reverse_lazy("admin:Sjak_sjakitem_changelist"),
                    },
                ],
            },
            {
                "title": _("Teknik"),
                "separator": True,
                "collapsible": True,
                "default_open": True,
                "items": [
                    {
                        "title": _("Teknik Bookinger"),
                        "icon": "calendar_add_on",
                        "link": reverse_lazy("admin:Teknik_teknikbooking_changelist"),
                    },
                    {
                        "title": _("Teknik Udstyr"),
                        "icon": "devices",
                        "link": reverse_lazy("admin:Teknik_teknikitem_changelist"),
                    },
                ],
            },
        ],
    },
}
