"""
Django settings for bookingsystem project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _
from unfold.contrib.constance.settings import UNFOLD_CONSTANCE_ADDITIONAL_FIELDS

from django.urls import reverse_lazy
from pathlib import Path
from dotenv import load_dotenv
import os

import os
from pathlib import Path

# Load .env files locally (optional)

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'slettenbooking@gmail.com')

# Debug setting
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Secret key
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'dev-secret-key-change-in-production')

# Allowed hosts
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h]
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
# Environment detection
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'dev')

# Database configuration
if ENVIRONMENT in ['staging', 'production']:
    # Use PostgreSQL for staging/production
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DATABASE_NAME'),
            'USER': os.environ.get('DATABASE_USERNAME'),
            'PASSWORD': os.environ.get('DATABASE_PASSWORD'),
            'HOST': os.environ.get('DATABASE_HOST', 'db'),
            'PORT': os.environ.get('DATABASE_PORT', '5432'),

            
        }
    }
elif ENVIRONMENT == 'dev':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    raise ValueError("ENVIRONMENT variable must be set to 'dev', 'staging', or 'production'")




# Application definition

INSTALLED_APPS = [
    'rest_framework',
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    "unfold.contrib.constance",  # optional, if django-constance package is used
    "django.contrib.admin",  # required
    'django_comments_xtd',
    'django_comments',
    'django.contrib.sites',  # Required by django-comments
    'constance',
    'simple_history',
    'organization',
    'django.contrib.staticfiles',
    'import_export',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'frontend',
    'core',
    'django_bootstrap5',
    'template_partials',
    'django_bootstrap_icons',
    'django_admin_listfilter_dropdown',
    'AktivitetsTeam',
    'Butikken',
    'Sjak',
    'Teknik',
    'SOS',
    'Foto',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

# -----------------------------
# Static files
# -----------------------------

STATIC_URL = 'static/'

if ENVIRONMENT in ['staging', 'production']:
    # The absolute path where collectstatic will dump files
    # This MUST match the path in your docker-compose web volume
    STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
else:
    # Local development settings
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    MEDIA_ROOT = BASE_DIR / 'media'

# These should be outside the if/else unless they change per env

ROOT_URLCONF = 'core.urls'
MEDIA_URL = '/media/'


CONSTANCE_REDIS_CONNECTION = {
    'host': os.environ.get('REDIS_HOST', 'redis'),
    'port': int(os.environ.get('REDIS_PORT', 6379)),
    'db': 0,
}

# Example for Cache
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get('REDIS_URL', 'redis://redis:6379/1'),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

CONSTANCE_CONFIG = {
    'THE_ANSWER': (42, 'Answer to the Ultimate Question of Life, '
                       'The Universe, and Everything'),
}
CONSTANCE_ADDITIONAL_FIELDS = {
    **UNFOLD_CONSTANCE_ADDITIONAL_FIELDS,

    # Example field configuration for select with choices. Not needed.
    "choice_field": [
        "django.forms.fields.ChoiceField",
        {
            "widget": "unfold.widgets.UnfoldAdminSelectWidget",
            "choices": (
                ("light-blue", "Light blue"),
                ("dark-blue", "Dark blue"),
            ),
        },
    ],
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# In settings.py
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
WSGI_APPLICATION = 'core.wsgi.application'



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'da-dk'
LANGUAGES = (
    ('da', 'Danish'),
    ('no', 'Norwegian'),
    ('en', 'English'),
)

TIME_ZONE = 'Europe/Copenhagen'
USE_L10N = True
USE_I18N = True
USE_TZ = True





SITE_ID = 1  # Required for django.contrib.sites

# Basic XTD Settings
COMMENTS_APP = 'django_comments_xtd'
COMMENTS_XTD_MAX_THREAD_LEVEL = 2  # How deep the replies go
COMMENTS_XTD_CONFIRM_EMAIL = False # Set to True if you want email verification


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'organization.Volunteer'
# Set the authentication backend to use Django's default ModelBackend
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL = 'login_user'

# Set the LOGIN_REDIRECT_URL to the URL where you want to redirect the user after successful login
LOGIN_REDIRECT_URL = '/'  # Change the URL to '/' for root URL redirection


UNFOLD = {
    "SITE_TITLE": "Admin",
    "SITE_HEADER": "SKS Admin",
    "SITE_SUBHEADER": "- Med lort på styret",
    "SITE_SYMBOL": "mode_heat",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": True,
    "BORDER_RADIUS": "6px",
    "COLORS": {
        "primary": {
            50: "#FFF0EB",
            100: "#FFE2D6",
            200: "#FFC8B3",
            300: "#FFAB8A",
            400: "#FF8E61",
            500: "#FF733C",
            600: "#FF733C",
            700: "#FF733C",
            800: "#FA4700",
            900: "#BD3500",
            950: "#802400",
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "dn": "🇩🇰",
                "en": "🇬🇧",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Organization"),
                "separator": True,
                "collapsible": True,
                "default_open": True,
                "items": [
                    {
                        "title": _("Brugere"),
                        "icon": "person",
                        "link": reverse_lazy("admin:organization_volunteer_changelist"),
                    },
                    {
                        "title": _("Teams"),
                        "icon": "people",
                        "link": reverse_lazy("admin:organization_team_changelist"),
                    },
                    {
                        "title": _("Events"),
                        "icon": "event",
                        "link": reverse_lazy("admin:organization_event_changelist"),
                    },
                ],
            },
            {
                "title": _("Butikken & Forplejning"),  # Added Butikken Section
                "separator": True,
                "collapsible": True,
                "default_open": True,
                "items": [
                    {
                        "title": _("Vareoversigt"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:Butikken_butikkenitem_changelist"),
                    },
                    {
                        "title": _("Vare Bookinger"),
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:Butikken_butikkenbooking_changelist"),
                    },
                    {
                        "title": _("Måltider"),
                        "icon": "restaurant_menu",
                        "link": reverse_lazy("admin:Butikken_mealplan_changelist"),
                    },
                    {
                        "title": _("Team Måltidsvalg"),
                        "icon": "assignment",
                        "link": reverse_lazy("admin:Butikken_teammealplan_changelist"),
                    },
                    {
                        "title": _("Opskrifter"),
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:Butikken_recipe_changelist"),
                    },
                ],
            },
            {
                "title": _("Aktivitetsteam"),
                "separator": True,
                "collapsible": True,
                "default_open": True,
                "items": [
                    {
                        "title": _("Bookinger"),
                        "icon": "calendar_add_on",
                        "link": reverse_lazy("admin:AktivitetsTeam_aktivitetsteambooking_changelist"),
                    },
                    {
                        "title": _("Aktiviteter"),
                        "icon": "hiking",
                        "link": reverse_lazy("admin:AktivitetsTeam_aktivitetsteamitem_changelist"),
                    },
                ],
            },
            {
                "title": _("Sjak"),
                "separator": True,
                "collapsible": True,
                "default_open": True,
                "items": [
                    {
                        "title": _("Sjak Bookinger"),
                        "icon": "calendar_add_on",
                        "link": reverse_lazy("admin:Sjak_sjakbooking_changelist"),
                    },
                    {
                        "title": _("Sjak sager"),
                        "icon": "home_repair_service",
                        "link": reverse_lazy("admin:Sjak_sjakitem_changelist"),
                    },
                ],
            },
            {
                "title": _("Teknik"),
                "separator": True,
                "collapsible": True,
                "default_open": True,
                "items": [
                    {
                        "title": _("Teknik Bookinger"),
                        "icon": "calendar_add_on",
                        "link": reverse_lazy("admin:Teknik_teknikbooking_changelist"),
                    },
                    {
                        "title": _("Teknik Udstyr"),
                        "icon": "devices",
                        "link": reverse_lazy("admin:Teknik_teknikitem_changelist"),
                    },
                ],
            },
            {
                "title": _("SOS"),
                "separator": True,
                "collapsible": True,
                "default_open": True,
                "items": [
                    {
                        "title": _("SOS Bookinger"),
                        "icon": "calendar_add_on",
                        "link": reverse_lazy("admin:SOS_sosbooking_changelist"),
                    },
                    {
                        "title": _("SOS Katalog"),
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:SOS_sositem_changelist"),
                    },
                ],
            },
            {
                "title": _("Foto"),
                "separator": True,
                "collapsible": True,
                "default_open": True,
                "items": [
                    {
                        "title": _("Foto Bookinger"),
                        "icon": "calendar_add_on",
                        "link": reverse_lazy("admin:Foto_fotobooking_changelist"),
                    },
                    {
                        "title": _("Udstyrskatalog"),
                        "icon": "photo_camera",
                        "link": reverse_lazy("admin:Foto_fotoitem_changelist"),
                    },
                ],
            },
        ],
    },
}
