# Generated by Django 5.2.10 on 2026-02-04 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AktivitetsTeam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AktivitetsTeamItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('bs_icon', models.CharField(default='bi-tag', help_text='Bootstrap icon name (f.eks. bi-rocket)', max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='aktivitetsteamitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aktivitetsteamitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='AktivitetsTeam.aktivitetsteamitemtype'),
        ),
    ]
