# Generated by Django 5.2.10 on 2026-02-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AktivitetsTeam', '0002_aktivitetsteamitemtype_aktivitetsteamitem_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivitetsteamitem',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='Indsæt link til YouTube video (valgfrit)', max_length=2000, null=True),
        ),
    ]
