# Generated by Django 5.2.10 on 2026-02-04 15:21

import map_location.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AktivitetsTeam', '0003_alter_aktivitetsteamitem_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitetsteamitem',
            name='location',
            field=map_location.fields.LocationField(blank=True, null=True, verbose_name='Placering'),
        ),
    ]
