# Generated by Django 5.2.10 on 2026-02-04 15:58

import map_location.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AktivitetsTeam', '0004_aktivitetsteamitem_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivitetsteamitem',
            name='location',
            field=map_location.fields.LocationField(blank=True, default='56.113991,9.665244', null=True, verbose_name='Placering'),
        ),
    ]
