# Generated by Django 5.2.10 on 2026-02-04 17:38

import map_location.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AktivitetsTeam', '0005_alter_aktivitetsteamitem_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktivitetsteambooking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='aktivitetsteambooking',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='aktivitetsteambooking',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='aktivitetsteambooking',
            name='location',
            field=map_location.fields.LocationField(help_text='Vælg placering på kortet'),
        ),
    ]
