# Generated by Django 5.2.10 on 2026-02-04 17:55

import map_location.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AktivitetsTeam', '0006_remove_aktivitetsteambooking_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivitetsteambooking',
            name='location',
            field=map_location.fields.LocationField(blank=True, default='56.114951,9.655592', null=True, verbose_name='Lokation'),
        ),
    ]
