# Generated by Django 5.1.6 on 2026-01-18 18:06

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0007_alter_volunteer_managers_volunteer_date_joined_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ButikkenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('content_normal', models.CharField(blank=True, max_length=100)),
                ('content_unit', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Butiksvare',
                'verbose_name_plural': 'Butiksvarer',
            },
        ),
        migrations.CreateModel(
            name='ButikkenItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('meal_date', models.DateField(default=datetime.date.today)),
                ('open_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('close_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Måltid',
                'verbose_name_plural': 'Måltider',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Måltidspakke',
                'verbose_name_plural': 'Måltidspakker',
            },
        ),
        migrations.CreateModel(
            name='ButikkenBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Udleveret', 'Udleveret')], default='Pending', max_length=10)),
                ('start', models.DateField(verbose_name='Start')),
                ('start_time', models.TimeField(verbose_name='Start_time')),
                ('date_used', models.DateField(blank=True, null=True, verbose_name='Dato brugt')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True)),
                ('remarks_internal', models.TextField(blank=True)),
                ('for_meal', models.CharField(choices=[('Aktivitet', 'Aktivitet'), ('Morgenmad', 'Morgenmad'), ('Frokost', 'Frokost'), ('Aftensmad', 'Aftensmad')], default='Pending', max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.team')),
                ('team_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Butikken.butikkenitem')),
            ],
            options={
                'verbose_name': 'Butiksbestilling',
                'verbose_name_plural': 'Butiksbestillinger',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Butikken.day')),
            ],
        ),
        migrations.CreateModel(
            name='MealBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.team')),
                ('team_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Butikken.meal')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Butikken.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='MealOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Butikken.mealplan')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Butikken.recipe')),
            ],
            options={
                'verbose_name': 'Måltidsvalgmulighed',
                'verbose_name_plural': 'Måltidsvalgmulighedr',
            },
        ),
        migrations.CreateModel(
            name='TeamMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('meal_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Butikken.mealoption')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Butikken.mealplan')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.team')),
                ('team_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Måltidsbestilling',
                'verbose_name_plural': 'Måltidsbestillinger',
            },
        ),
    ]
