# Generated by Django 5.2.10 on 2026-04-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Butikken', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='butikkenbooking',
            old_name='start',
            new_name='start_date',
        ),
    ]
